modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="regrowth"
version="${file.jarVersion}"
displayName="Regrowth Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/regrowth"
logoFile="RegrowthMod.png"
authors="MacTso, Lupicus"
description='''Regrowth Mod.'''
[[dependencies.regrowth]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.regrowth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,1.15)"
    ordering="NONE"
    side="SERVER"
